import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import clientPromise from '../../lib/mongodb';
import { Link } from "react-router-dom";
import { useSession, signOut, getSession } from "next-auth/react";

/* eslint react/no-string-refs: 0 */

export default function Home({ isConnected }) {

  const [restaurants, setRestaurants] = useState([]);

  const { data: session, status } = useSession({ required: true });

  useEffect(() => {
    (async () => {
      const results = await fetch("/api/list");
      const resultsJson = await results.json();
      setRestaurants(resultsJson);
    })();
  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link ref='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome, {session.user.username}</h1>
        <br />
        <div className={styles.grid}>
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  try {
    await clientPromise
    return {
      props: { isConnected: true },
    }
  } catch (e) {
    console.log(e)
    return {
      props: { isConnected: false },
    }
  }
}
